FROM rust:latest AS builder
WORKDIR /app

#COPY Cargo.toml Cargo.lock ./
#COPY tuah-server/Cargo.toml ./tuah-server/Cargo.toml
#RUN mkdir -p tuah-server/src && echo "fn main() {}" > tuah-server/src/main.rs

COPY ../../tuah-turn .

RUN cargo build --release

FROM debian:buster-slim

WORKDIR /app

COPY --from=builder /app/target/release/tuah-turn /usr/local/bin/tuah-turn

ENTRYPOINT [ "tuah-turn" ] 